### ISSUE TITLE
Clean up database

### ISSUE THREAD

**Issue by BrianZ1** [chrissbendel/professor-rating#10]
Remove avg, sum, count off database
Calculate stats as we find reviews

**Comment by chrissbendel** [comment]
The review itself should have an ID that relates to a school, class, or professor.

The review can have a single thing out of 10, or a thumbs up or thumbs down, 5 stars, whatever the system is.

I like thumbs up/down (will be simpler).

When you view a school, you can query all of the reviews that belong to that school ID (same with profs, and classes). Then we can display all the reviews for the relevant school (these will go in the detail view of each page, eg. Champlain College's specific page will have a list of reviews).
